backend:
  name: git-gateway
  repo: sanampatel/staticpress-demo
  branch: master
  squash_merges: true
publish_mode: editorial_workflow
media_folder: source/images
collections:
  - name: "categories"
    label: "Categories"
    label_singular: "Category"
    folder: "source/_categories"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", default: "Title"}
  - name: "tags"
    label: "Tags"
    label_singular: "Tag"
    folder: "source/_tags"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", default: "Title"}
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    folder: "source/_posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", default: "Title"}
      - {label: "Author Name", name: "authorname", widget: "string", required: false}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "SEOTitle", name: "seotitle", widget: "string", default: "SEO Title"}
      - {label: "SEO Keywords", name: "seokeywords", widget: "string", default: SEO Keywords}
      - {label: "SEO Description", name: "seodescription", widget: "string", default: SEO Description}
      - {label: "Categories", name: "categories", widget: "relation", collection: 'categories', searchFields: ["title"], displayFields: ["title"], valueField: "title", default: ""}
      - {label: "Is Posts", name: "isPosts", widget: "boolean", default: true}
      - {label: "Image Filename", name: "image", widget: "image", required: true}
      - {label: "Comments", name: "comments", widget: "boolean", default: true}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "settings"
    label: "Settings"
    label_singular: "Setting"
    folder: "source/_settings"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", default: "Setting"}
      - {label: "SEOTitle", name: "seotitle", widget: "string", default: "SEO Title"}
      - {label: "SEO Keywords", name: "seokeywords", widget: "string", default: SEO Keywords}
      - {label: "SEO Description", name: "seodescription", widget: "string", default: SEO Description}
      - {label: "About author", name: "aboutauthor", widget: "string", default: "About author"}
      - {label: "Post page title", name: "postpagetitle", widget: "string", default: "Post page title"}
      - {label: "Custom Header", name: "customheader", widget: "markdown"}
      - {label: "Custom Footer", name: "customfooter", widget: "markdown"}
  - name: "customPages"
    label: "CustomPages"
    label_singular: "CustomPages"
    folder: "source/_customPages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink Override", name: "link", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "SEOTitle", name: "seotitle", widget: "string", required: false}
      - {label: "SEO keywords", name: "seokeywords", widget: "string", required: false}
      - {label: "SEO description", name: "seodescription", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "markdown"}
  - label: "Sliders"
    name: "sliders"
    folder: "source/_sliders"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Images", name: "image", widget: "image"}
  - label: "Nav"
    name: "nav"
    files:
      - label: "Navigation"
        name: "navigation"
        delete: false
        file: "source/navigation.json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - {label: "Text", name: "text", widget: string}
              - {label: "Url", name: "url", widget: string}
              - label: "MetaItems"
                name: "metaitems"
                widget: "list"
                fields:
                  - {label: "Text", name: "text", widget: string, required: false}
                  - {label: "Url", name: "url", widget: string, required: false}